project:
  type: website

website:
  title: "Farm Hill Education Trust"
  navbar:
    background: primary
    left:
      - people/index.qmd
      - contact/index.qmd
      - about/index.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: false



